### ISSUE TITLE
Add missing basics data structures!

### ISSUE THREAD

**Issue by nitinprakash96** [nitinprakash96/Data-structures#13]
Add more missing basic data structure algorithms.
Eg.: DFS is missing in graphs section. And don't forget to write what the code is about in comments.
If possible, make three files separately for your code. The main, header and function definition file.

**Comment by prashant2018** [comment]
Hi, I would like to work on this

**Comment by nitinprakash96** [comment]
Yea sure! Just make sure you do the things mentioned above. @prashant2018

**Comment by NamanArora** [comment]
Added dfs. What else do you need? 
#15

**Comment by nitinprakash96** [comment]
Probably a code or two on greedy algorithms would be nice

**Comment by prashant2018** [comment]
Added bit algorithm #16

**Comment by praran26** [comment]
Added RMQ using Sparse Table #24

**Comment by vharsh** [comment]
Added Floyd's Circle detection algorithm #25
